-- Casino: consolidated one-shot setup for the dedicated Supabase project.
-- Generated by concatenating supabase/migrations/001_users.sql through
-- 007_server_authority.sql, in order, unmodified.
--
-- Purpose: paste this single file into the Supabase SQL Editor once, instead
-- of running 7 files individually. NOT itself a numbered migration — do not
-- move this into supabase/migrations/, or `supabase db push` may pick it up
-- as an 8th migration and re-run already-applied statements.
--
-- KNOWN LIMITATION: most statements are idempotent (CREATE TABLE IF NOT
-- EXISTS, CREATE OR REPLACE FUNCTION, ADD COLUMN IF NOT EXISTS), but
-- CREATE POLICY is NOT — Postgres has no CREATE POLICY IF NOT EXISTS.
-- Running this file a second time against a database where these policies
-- already exist will fail on the first duplicate CREATE POLICY statement.
-- Safe for a first run against an empty project (verified 0 existing tables
-- at time of writing); do not re-run blindly against a partially-set-up DB.

-- ============================================================
-- 001_users.sql
-- ============================================================
-- Casino Royale - Users Table
-- Uses Clerk User ID (TEXT) as primary key, NOT Supabase auth.users UUID.
-- RLS uses JWT sub claim injected by Clerk via getToken({ template: 'supabase' }).

CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,                          -- Clerk User ID (user_xxx...)
    username TEXT NOT NULL,
    email TEXT,
    avatar_url TEXT,
    balance DECIMAL(20, 2) DEFAULT 1000.00 CHECK (balance >= 0),
    xp BIGINT DEFAULT 0,
    level INTEGER DEFAULT 1,
    rank TEXT DEFAULT 'BRONZE',
    rakeback_pool DECIMAL(20, 4) DEFAULT 0.00,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- Users can only read and update their own row.
-- Admin-Client (service role) bypasses RLS for webhook upserts.
CREATE POLICY "users_select_own" ON users
    FOR SELECT USING ((auth.jwt() ->> 'sub') = id);

CREATE POLICY "users_update_own" ON users
    FOR UPDATE USING ((auth.jwt() ->> 'sub') = id);

CREATE INDEX IF NOT EXISTS idx_users_id ON users(id);

-- ============================================================
-- 002_wallet.sql
-- ============================================================
-- Casino Royale - Wallet Audit Trail & Session Tracking
-- NOTE: user balance lives in users.balance (single source of truth).
-- wallet_transactions is an immutable audit log only — never a balance source.
-- Adapted from casino-platform baseline RLS pattern.

-- Immutable audit trail for every balance change
-- amount: positive = credit (win/purchase), negative = debit (bet)
CREATE TABLE IF NOT EXISTS wallet_transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    game TEXT,                   -- 'slots', 'roulette', 'crash', 'dice', 'purchase', 'bonus'
    type TEXT NOT NULL,          -- 'bet', 'win', 'crash_pending', 'purchase', 'bonus'
    amount DECIMAL(20, 2) NOT NULL,
    balance_after DECIMAL(20, 2) NOT NULL,
    metadata JSONB,              -- Game-specific details (multiplier, result, seed hash, crashPoint)
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Per-session stats for history & analytics pages
CREATE TABLE IF NOT EXISTS game_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    game TEXT NOT NULL,
    started_at TIMESTAMPTZ DEFAULT now(),
    ended_at TIMESTAMPTZ,
    total_bet DECIMAL(20, 2) DEFAULT 0.00,
    total_won DECIMAL(20, 2) DEFAULT 0.00,
    hands_played INTEGER DEFAULT 0
);

-- Row Level Security
ALTER TABLE wallet_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE game_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "transactions_select_own" ON wallet_transactions
    FOR SELECT USING ((auth.jwt() ->> 'sub') = user_id);

CREATE POLICY "sessions_select_own" ON game_sessions
    FOR SELECT USING ((auth.jwt() ->> 'sub') = user_id);

-- Indexes for critical query paths
CREATE INDEX IF NOT EXISTS idx_transactions_user ON wallet_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_game ON wallet_transactions(game);
CREATE INDEX IF NOT EXISTS idx_transactions_created ON wallet_transactions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON game_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_game ON game_sessions(game);

-- ============================================================
-- 003_provably_fair.sql
-- ============================================================
-- Casino Royale - Provably Fair Seeds & Atomic Bet Stored Procedures
-- All procedures operate on users.balance as the single source of truth.
-- SECURITY DEFINER: runs with creator privileges, safe for RPC calls.

-- Server/client seeds per user for provably fair verification
CREATE TABLE IF NOT EXISTS seeds (
    user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    server_seed TEXT NOT NULL,
    server_seed_hash TEXT NOT NULL,
    client_seed TEXT NOT NULL,
    nonce INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE seeds ENABLE ROW LEVEL SECURITY;

-- Users can read their own seed hash (not the raw server seed)
CREATE POLICY "seeds_select_own" ON seeds
    FOR SELECT USING ((auth.jwt() ->> 'sub') = user_id);

-- Atomic debit: check-and-deduct in one statement, write audit row.
-- Raises exception on insufficient balance (caught by API route).
CREATE OR REPLACE FUNCTION place_bet(
    p_user_id TEXT,
    p_amount DECIMAL,
    p_game TEXT
) RETURNS DECIMAL AS $$
DECLARE
    v_new_balance DECIMAL;
BEGIN
    UPDATE users
    SET balance = balance - p_amount,
        updated_at = now()
    WHERE id = p_user_id AND balance >= p_amount
    RETURNING balance INTO v_new_balance;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Insufficient balance';
    END IF;

    INSERT INTO wallet_transactions (user_id, game, type, amount, balance_after)
    VALUES (p_user_id, p_game, 'bet', -p_amount, v_new_balance);

    RETURN v_new_balance;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Atomic credit: add payout + recalculate XP/level, write audit row if payout > 0.
-- Returns updated balance, xp, level.
CREATE OR REPLACE FUNCTION settle_bet(
    p_user_id TEXT,
    p_payout DECIMAL,
    p_xp_gain INTEGER,
    p_game TEXT
) RETURNS TABLE(balance DECIMAL, xp BIGINT, level INTEGER) AS $$
DECLARE
    v_new_balance DECIMAL;
    v_new_xp BIGINT;
    v_new_level INTEGER;
BEGIN
    UPDATE users
    SET balance = balance + p_payout,
        xp = xp + p_xp_gain,
        level = GREATEST(1, FLOOR(SQRT((users.xp + p_xp_gain) / 100.0))::INTEGER + 1),
        updated_at = now()
    WHERE id = p_user_id
    RETURNING users.balance, users.xp, users.level
    INTO v_new_balance, v_new_xp, v_new_level;

    IF p_payout > 0 THEN
        INSERT INTO wallet_transactions (user_id, game, type, amount, balance_after)
        VALUES (p_user_id, p_game, 'win', p_payout, v_new_balance);
    END IF;

    RETURN QUERY SELECT v_new_balance, v_new_xp, v_new_level;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================
-- 004_vip_tiers.sql
-- ============================================================
-- Casino Royale - VIP Tier & Rank Configuration
-- Global, read-only configuration tables for the gamification system.
-- These values can be tuned in Supabase without a code deploy.

-- VIP Tiers (XP-based, used for rakeback calculation)
CREATE TABLE IF NOT EXISTS vip_tiers (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    min_xp BIGINT NOT NULL CHECK (min_xp >= 0),
    rakeback DECIMAL(5,4) NOT NULL CHECK (rakeback >= 0),
    color TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE vip_tiers ENABLE ROW LEVEL SECURITY;

-- Configuration is public and read-only for clients
CREATE POLICY "vip_tiers_select_public" ON vip_tiers
    FOR SELECT USING (true);

INSERT INTO vip_tiers (name, min_xp, rakeback, color, sort_order) VALUES
('BRONZE', 0, 0.0100, '#cd7f32', 1),
('SILVER', 5000, 0.0200, '#c0c0c0', 2),
('GOLD', 25000, 0.0300, '#ffd700', 3),
('PLATINUM', 100000, 0.0500, '#e5e4e2', 4),
('DIAMOND', 500000, 0.1000, '#b9f2ff', 5)
ON CONFLICT (name) DO UPDATE SET
    min_xp = EXCLUDED.min_xp,
    rakeback = EXCLUDED.rakeback,
    color = EXCLUDED.color,
    sort_order = EXCLUDED.sort_order,
    is_active = EXCLUDED.is_active;

-- Ranks (Level-based, used for UI and rank perks)
CREATE TABLE IF NOT EXISTS ranks (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    min_level INTEGER NOT NULL CHECK (min_level >= 1),
    color TEXT NOT NULL,
    rakeback DECIMAL(5,4) NOT NULL CHECK (rakeback >= 0),
    perks TEXT[] NOT NULL DEFAULT '{}',
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE ranks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "ranks_select_public" ON ranks
    FOR SELECT USING (true);

INSERT INTO ranks (name, min_level, color, rakeback, perks, sort_order) VALUES
('Bronze', 1, '#CD7F32', 0.0100, ARRAY['Daily Missions','Basic Rakeback'], 1),
('Silver', 10, '#C0C0C0', 0.0120, ARRAY['Priority Support','Enhanced Rakeback'], 2),
('Gold', 25, '#FFD700', 0.0150, ARRAY['Private Access','Weekly Bonuses'], 3),
('Platinum', 50, '#E5E4E2', 0.0180, ARRAY['VIP Manager','Custom Cases'], 4),
('Diamond', 100, '#B9F2FF', 0.0200, ARRAY['Instant Withdrawals','Global Recognition'], 5)
ON CONFLICT (name) DO UPDATE SET
    min_level = EXCLUDED.min_level,
    color = EXCLUDED.color,
    rakeback = EXCLUDED.rakeback,
    perks = EXCLUDED.perks,
    sort_order = EXCLUDED.sort_order,
    is_active = EXCLUDED.is_active;

-- Indexes for sorted reads
CREATE INDEX IF NOT EXISTS idx_vip_tiers_sort ON vip_tiers(sort_order);
CREATE INDEX IF NOT EXISTS idx_ranks_sort ON ranks(sort_order);

-- ============================================================
-- 005_anonymous_sessions.sql
-- ============================================================
-- Casino Royale - Anonymous Session Storage
-- Allows unauthenticated players to persist progress (xp, level, rank, rakeback)
-- under a client-generated session id. On login the session can be migrated
-- into the authenticated users table.

CREATE TABLE IF NOT EXISTS anonymous_sessions (
    id TEXT PRIMARY KEY,                       -- client-generated UUIDv4
    xp BIGINT DEFAULT 0 CHECK (xp >= 0),
    level INTEGER DEFAULT 1 CHECK (level >= 1),
    rank TEXT DEFAULT 'Bronze',
    rakeback_pool DECIMAL(20,4) DEFAULT 0.00 CHECK (rakeback_pool >= 0),
    data JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT now(),
    last_active_at TIMESTAMPTZ DEFAULT now(),
    migrated_to_user_id TEXT REFERENCES users(id) ON DELETE SET NULL
);

ALTER TABLE anonymous_sessions ENABLE ROW LEVEL SECURITY;

-- Only the holder of the matching session id may read/update the row.
-- We pass the session id via a custom claim or use a service-role route for migration.
CREATE POLICY "anonymous_sessions_select_own" ON anonymous_sessions
    FOR SELECT USING (
        (auth.jwt() -> 'app_metadata' ->> 'session_id') = id
        OR (auth.jwt() ->> 'sub') = migrated_to_user_id
    );

CREATE POLICY "anonymous_sessions_update_own" ON anonymous_sessions
    FOR UPDATE USING (
        (auth.jwt() -> 'app_metadata' ->> 'session_id') = id
    );

CREATE POLICY "anonymous_sessions_insert_own" ON anonymous_sessions
    FOR INSERT WITH CHECK (
        (auth.jwt() -> 'app_metadata' ->> 'session_id') = id
    );

CREATE INDEX IF NOT EXISTS idx_anonymous_sessions_migrated
    ON anonymous_sessions(migrated_to_user_id)
    WHERE migrated_to_user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_anonymous_sessions_last_active
    ON anonymous_sessions(last_active_at);

-- Atomic migration: copy anonymous session progress into users if the user has less XP.
-- Returns the resulting balance/xp/level from the users table.
CREATE OR REPLACE FUNCTION migrate_anonymous_session(
    p_session_id TEXT,
    p_user_id TEXT
) RETURNS TABLE(balance DECIMAL, xp BIGINT, level INTEGER, rank TEXT, rakeback_pool DECIMAL) AS $$
DECLARE
    v_session anonymous_sessions%ROWTYPE;
    v_user users%ROWTYPE;
BEGIN
    SELECT * INTO v_session FROM anonymous_sessions WHERE id = p_session_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Session not found';
    END IF;

    IF v_session.migrated_to_user_id IS NOT NULL AND v_session.migrated_to_user_id != p_user_id THEN
        RAISE EXCEPTION 'Session already migrated to a different user';
    END IF;

    SELECT * INTO v_user FROM users WHERE id = p_user_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'User not found';
    END IF;

    -- Migrate only if the anonymous session has more progress than the existing user.
    IF v_session.xp > COALESCE(v_user.xp, 0) THEN
        UPDATE users
        SET xp = v_session.xp,
            level = GREATEST(v_user.level, v_session.level),
            rank = COALESCE(NULLIF(v_session.rank, ''), v_user.rank),
            rakeback_pool = v_user.rakeback_pool + v_session.rakeback_pool,
            updated_at = now()
        WHERE id = p_user_id;
    ELSE
        -- Just add the rakeback pool; keep existing rank/xp/level.
        UPDATE users
        SET rakeback_pool = v_user.rakeback_pool + v_session.rakeback_pool,
            updated_at = now()
        WHERE id = p_user_id;
    END IF;

    -- Mark session as migrated
    UPDATE anonymous_sessions
    SET migrated_to_user_id = p_user_id,
        last_active_at = now()
    WHERE id = p_session_id;

    RETURN QUERY SELECT u.balance, u.xp, u.level, u.rank, u.rakeback_pool
                 FROM users u WHERE u.id = p_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Lightweight upsert to keep anonymous session state in sync from the client.
CREATE OR REPLACE FUNCTION upsert_anonymous_session(
    p_session_id TEXT,
    p_xp BIGINT,
    p_level INTEGER,
    p_rank TEXT,
    p_rakeback_pool DECIMAL
) RETURNS VOID AS $$
BEGIN
    INSERT INTO anonymous_sessions (id, xp, level, rank, rakeback_pool, last_active_at)
    VALUES (p_session_id, p_xp, p_level, p_rank, p_rakeback_pool, now())
    ON CONFLICT (id) DO UPDATE SET
        xp = EXCLUDED.xp,
        level = EXCLUDED.level,
        rank = EXCLUDED.rank,
        rakeback_pool = EXCLUDED.rakeback_pool,
        last_active_at = now()
    WHERE anonymous_sessions.migrated_to_user_id IS NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================
-- 006_game_configs.sql
-- ============================================================
-- Casino Royale - Global Game Configuration
-- Centralized tunable parameters: bet limits, house edge, multipliers, XP formula.
-- Values can be changed in Supabase without a code deploy.

CREATE TABLE IF NOT EXISTS game_configs (
    id SERIAL PRIMARY KEY,
    category TEXT NOT NULL,      -- e.g. 'limits', 'crash', 'roulette'
    config_key TEXT NOT NULL,    -- mirrors category for grouped configs
    value JSONB NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    updated_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(category, config_key)
);

ALTER TABLE game_configs ENABLE ROW LEVEL SECURITY;

-- Configuration is public and read-only for clients
CREATE POLICY "game_configs_select_public" ON game_configs
    FOR SELECT USING (true);

-- Seed with values currently hardcoded in the application
INSERT INTO game_configs (category, config_key, value, description) VALUES
('limits', 'limits', '{"bet_min":0.10,"bet_max":10000.00,"max_bet_hardcap":100000000.00}', 'Bet limits and hardcap'),
('crash', 'crash', '{"house_edge":0.01}', 'Crash house edge (1%)'),
('roulette', 'roulette', '{"multipliers":{"STRAIGHT":35,"COLOR":2,"EVEN_ODD":2,"RANGE":2,"DOZEN":2,"COLUMN":2,"VOISINS":2.1176,"TIERS":3.0,"ORPHELINS":4.5}}', 'Roulette payout multipliers'),
('blackjack', 'blackjack', '{"max_payout_factor":2.5}', 'Maximum allowed client-reported payout factor'),
('slots', 'slots', '{"paytable":{"match_5_base":50,"match_4_base":10,"match_3_base":2,"symbol_weight":0.5}}', 'Slots paytable parameters'),
('xp', 'xp', '{"max_xp_per_bet":10000,"max_level":100,"base_multiplier":10,"level_formula_sqrt_divisor":100,"level_multiplier_step":100,"level_multiplier_max":5}', 'XP formula parameters')
ON CONFLICT (category, config_key) DO UPDATE SET
    value = EXCLUDED.value,
    description = EXCLUDED.description,
    is_active = EXCLUDED.is_active,
    updated_at = now();

CREATE INDEX IF NOT EXISTS idx_game_configs_category ON game_configs(category);

-- ============================================================
-- 007_server_authority.sql
-- ============================================================
-- Server-authoritative, idempotent wallet settlement and stateful game rounds.
-- Apply with a privileged migration role. Browser roles never receive execute access.

ALTER TABLE wallet_transactions ADD COLUMN IF NOT EXISTS request_id UUID;
ALTER TABLE wallet_transactions ADD COLUMN IF NOT EXISTS result_id UUID;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'wallet_transactions_user_request_key'
  ) THEN
    ALTER TABLE wallet_transactions
      ADD CONSTRAINT wallet_transactions_user_request_key UNIQUE (user_id, request_id);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS game_rounds (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  request_id UUID NOT NULL,
  game TEXT NOT NULL CHECK (game IN ('CRASH', 'BLACKJACK')),
  bet_amount NUMERIC(20, 2) NOT NULL CHECK (bet_amount > 0),
  status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'SETTLED')),
  state JSONB NOT NULL DEFAULT '{}'::jsonb,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, request_id)
);

ALTER TABLE game_rounds ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_game_rounds_active
  ON game_rounds(user_id, game, status, created_at DESC);

CREATE OR REPLACE FUNCTION casino_rank_for_level(p_level INTEGER)
RETURNS TEXT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT COALESCE(
    (SELECT name FROM ranks WHERE is_active AND min_level <= p_level ORDER BY min_level DESC LIMIT 1),
    'Bronze'
  );
$$;

CREATE OR REPLACE FUNCTION settle_game_bet(
  p_user_id TEXT,
  p_request_id UUID,
  p_result_id UUID,
  p_game TEXT,
  p_amount NUMERIC,
  p_payout NUMERIC,
  p_xp_gain BIGINT,
  p_result JSONB
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_user users%ROWTYPE;
  v_existing wallet_transactions%ROWTYPE;
  v_balance NUMERIC(20, 2);
  v_xp BIGINT;
  v_level INTEGER;
  v_rank TEXT;
  v_transaction_id UUID;
  v_response JSONB;
BEGIN
  IF p_user_id IS NULL OR p_user_id = '' OR p_request_id IS NULL OR p_result_id IS NULL THEN
    RAISE EXCEPTION 'Invalid settlement identity';
  END IF;
  IF p_game NOT IN ('DICE', 'ROULETTE', 'SLOTS') OR p_amount <= 0 OR p_payout < 0
     OR p_xp_gain < 0 OR p_xp_gain > 10000 THEN
    RAISE EXCEPTION 'Invalid settlement values';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtextextended(p_user_id, 0));

  SELECT * INTO v_existing
  FROM wallet_transactions
  WHERE user_id = p_user_id AND request_id = p_request_id;

  IF FOUND THEN RETURN (v_existing.metadata -> 'response') || jsonb_build_object('replayed', true); END IF;

  INSERT INTO users (id, username)
  VALUES (p_user_id, left(p_user_id, 64))
  ON CONFLICT (id) DO NOTHING;

  SELECT * INTO v_user FROM users WHERE id = p_user_id FOR UPDATE;
  IF v_user.balance < p_amount THEN RAISE EXCEPTION 'Insufficient balance'; END IF;

  v_balance := round((v_user.balance - p_amount + p_payout)::numeric, 2);
  v_xp := v_user.xp + p_xp_gain;
  v_level := LEAST(100, floor(sqrt(v_xp::numeric / 100))::integer + 1);
  v_rank := casino_rank_for_level(v_level);

  UPDATE users SET balance = v_balance, xp = v_xp, level = v_level,
    rank = v_rank, updated_at = now() WHERE id = p_user_id;

  INSERT INTO wallet_transactions
    (user_id, game, type, amount, balance_after, request_id, result_id, metadata)
  VALUES
    (p_user_id, lower(p_game), 'bet_settled', p_payout - p_amount, v_balance,
     p_request_id, p_result_id, '{}'::jsonb)
  RETURNING id INTO v_transaction_id;

  v_response := jsonb_build_object(
    'balance', v_balance, 'xp', v_xp, 'level', v_level, 'rank', v_rank,
    'transactionId', v_transaction_id, 'result', p_result, 'replayed', false
  );
  UPDATE wallet_transactions SET metadata = jsonb_build_object('response', v_response)
    WHERE id = v_transaction_id;
  RETURN v_response;
END;
$$;

CREATE OR REPLACE FUNCTION start_game_round(
  p_user_id TEXT,
  p_request_id UUID,
  p_game TEXT,
  p_amount NUMERIC,
  p_state JSONB
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_user users%ROWTYPE;
  v_round game_rounds%ROWTYPE;
  v_existing wallet_transactions%ROWTYPE;
  v_balance NUMERIC(20, 2);
  v_transaction_id UUID;
  v_response JSONB;
BEGIN
  IF p_game NOT IN ('CRASH', 'BLACKJACK') OR p_amount <= 0 OR p_request_id IS NULL THEN
    RAISE EXCEPTION 'Invalid round values';
  END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended(p_user_id, 0));

  SELECT * INTO v_round FROM game_rounds
    WHERE user_id = p_user_id AND request_id = p_request_id;
  IF FOUND THEN
    SELECT * INTO v_existing FROM wallet_transactions WHERE user_id = p_user_id AND request_id = p_request_id;
    RETURN (v_existing.metadata -> 'response') || jsonb_build_object('replayed', true);
  END IF;

  INSERT INTO users (id, username) VALUES (p_user_id, left(p_user_id, 64))
    ON CONFLICT (id) DO NOTHING;
  SELECT * INTO v_user FROM users WHERE id = p_user_id FOR UPDATE;
  IF v_user.balance < p_amount THEN RAISE EXCEPTION 'Insufficient balance'; END IF;

  v_balance := round((v_user.balance - p_amount)::numeric, 2);
  UPDATE users SET balance = v_balance, updated_at = now() WHERE id = p_user_id;
  INSERT INTO game_rounds(user_id, request_id, game, bet_amount, state)
    VALUES (p_user_id, p_request_id, p_game, p_amount, p_state)
    RETURNING * INTO v_round;
  INSERT INTO wallet_transactions
    (user_id, game, type, amount, balance_after, request_id, metadata)
    VALUES (p_user_id, lower(p_game), 'round_started', -p_amount, v_balance,
      p_request_id, '{}'::jsonb)
    RETURNING id INTO v_transaction_id;

  v_response := jsonb_build_object(
    'roundId', v_round.id, 'state', v_round.state, 'version', v_round.version,
    'balance', v_balance, 'xp', v_user.xp, 'level', v_user.level,
    'rank', v_user.rank, 'transactionId', v_transaction_id, 'replayed', false
  );
  UPDATE wallet_transactions SET metadata = jsonb_build_object('response', v_response)
    WHERE id = v_transaction_id;
  RETURN v_response;
END;
$$;

CREATE OR REPLACE FUNCTION settle_game_round(
  p_user_id TEXT,
  p_round_id UUID,
  p_request_id UUID,
  p_result_id UUID,
  p_payout NUMERIC,
  p_xp_gain BIGINT,
  p_result JSONB
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_user users%ROWTYPE;
  v_round game_rounds%ROWTYPE;
  v_existing wallet_transactions%ROWTYPE;
  v_balance NUMERIC(20, 2);
  v_xp BIGINT;
  v_level INTEGER;
  v_rank TEXT;
  v_transaction_id UUID;
  v_response JSONB;
BEGIN
  IF p_request_id IS NULL OR p_result_id IS NULL OR p_payout < 0
     OR p_xp_gain < 0 OR p_xp_gain > 10000 THEN RAISE EXCEPTION 'Invalid settlement values'; END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended(p_user_id, 0));

  SELECT * INTO v_existing FROM wallet_transactions
    WHERE user_id = p_user_id AND request_id = p_request_id;
  IF FOUND THEN RETURN (v_existing.metadata -> 'response') || jsonb_build_object('replayed', true); END IF;

  SELECT * INTO v_round FROM game_rounds
    WHERE id = p_round_id AND user_id = p_user_id FOR UPDATE;
  IF NOT FOUND OR v_round.status <> 'ACTIVE' THEN RAISE EXCEPTION 'Round is not active'; END IF;
  SELECT * INTO v_user FROM users WHERE id = p_user_id FOR UPDATE;

  v_balance := round((v_user.balance + p_payout)::numeric, 2);
  v_xp := v_user.xp + p_xp_gain;
  v_level := LEAST(100, floor(sqrt(v_xp::numeric / 100))::integer + 1);
  v_rank := casino_rank_for_level(v_level);
  UPDATE users SET balance = v_balance, xp = v_xp, level = v_level,
    rank = v_rank, updated_at = now() WHERE id = p_user_id;
  UPDATE game_rounds SET status = 'SETTLED', state = state || jsonb_build_object('result', p_result),
    version = version + 1, updated_at = now() WHERE id = p_round_id;
  INSERT INTO wallet_transactions
    (user_id, game, type, amount, balance_after, request_id, result_id, metadata)
    VALUES (p_user_id, lower(v_round.game), 'round_settled', p_payout, v_balance,
      p_request_id, p_result_id, '{}'::jsonb)
    RETURNING id INTO v_transaction_id;

  v_response := jsonb_build_object(
    'balance', v_balance, 'xp', v_xp, 'level', v_level, 'rank', v_rank,
    'transactionId', v_transaction_id, 'result', p_result, 'replayed', false
  );
  UPDATE wallet_transactions SET metadata = jsonb_build_object('response', v_response)
    WHERE id = v_transaction_id;
  RETURN v_response;
END;
$$;

REVOKE ALL ON TABLE game_rounds FROM anon, authenticated;
REVOKE ALL ON FUNCTION casino_rank_for_level(INTEGER) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION settle_game_bet(TEXT, UUID, UUID, TEXT, NUMERIC, NUMERIC, BIGINT, JSONB) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION start_game_round(TEXT, UUID, TEXT, NUMERIC, JSONB) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION settle_game_round(TEXT, UUID, UUID, UUID, NUMERIC, BIGINT, JSONB) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION settle_game_bet(TEXT, UUID, UUID, TEXT, NUMERIC, NUMERIC, BIGINT, JSONB) TO service_role;
GRANT EXECUTE ON FUNCTION start_game_round(TEXT, UUID, TEXT, NUMERIC, JSONB) TO service_role;
GRANT EXECUTE ON FUNCTION settle_game_round(TEXT, UUID, UUID, UUID, NUMERIC, BIGINT, JSONB) TO service_role;

CREATE OR REPLACE FUNCTION advance_blackjack_round(
  p_user_id TEXT, p_round_id UUID, p_request_id UUID, p_result_id UUID,
  p_expected_version INTEGER, p_new_state JSONB, p_additional_bet NUMERIC,
  p_settled BOOLEAN, p_payout NUMERIC, p_xp_gain BIGINT, p_result JSONB
) RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE
  v_user users%ROWTYPE; v_round game_rounds%ROWTYPE; v_existing wallet_transactions%ROWTYPE;
  v_balance NUMERIC(20, 2); v_xp BIGINT; v_level INTEGER; v_rank TEXT;
  v_transaction_id UUID; v_response JSONB;
BEGIN
  IF p_request_id IS NULL OR p_result_id IS NULL OR p_expected_version < 1
     OR p_additional_bet < 0 OR p_payout < 0 OR p_xp_gain < 0 OR p_xp_gain > 10000 THEN
    RAISE EXCEPTION 'Invalid blackjack action';
  END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended(p_user_id, 0));
  SELECT * INTO v_existing FROM wallet_transactions
    WHERE user_id = p_user_id AND request_id = p_request_id;
  IF FOUND THEN RETURN (v_existing.metadata -> 'response') || jsonb_build_object('replayed', true); END IF;
  SELECT * INTO v_round FROM game_rounds
    WHERE id = p_round_id AND user_id = p_user_id AND game = 'BLACKJACK' FOR UPDATE;
  IF NOT FOUND OR v_round.status <> 'ACTIVE' OR v_round.version <> p_expected_version THEN
    RAISE EXCEPTION 'Stale or inactive blackjack round';
  END IF;
  SELECT * INTO v_user FROM users WHERE id = p_user_id FOR UPDATE;
  IF v_user.balance < p_additional_bet THEN RAISE EXCEPTION 'Insufficient balance'; END IF;
  v_balance := round((v_user.balance - p_additional_bet + CASE WHEN p_settled THEN p_payout ELSE 0 END)::numeric, 2);
  v_xp := v_user.xp + CASE WHEN p_settled THEN p_xp_gain ELSE 0 END;
  v_level := LEAST(100, floor(sqrt(v_xp::numeric / 100))::integer + 1);
  v_rank := casino_rank_for_level(v_level);
  UPDATE users SET balance = v_balance, xp = v_xp, level = v_level,
    rank = v_rank, updated_at = now() WHERE id = p_user_id;
  UPDATE game_rounds SET bet_amount = bet_amount + p_additional_bet, state = p_new_state,
    status = CASE WHEN p_settled THEN 'SETTLED' ELSE 'ACTIVE' END,
    version = version + 1, updated_at = now() WHERE id = p_round_id;
  INSERT INTO wallet_transactions
    (user_id, game, type, amount, balance_after, request_id, result_id, metadata)
  VALUES (p_user_id, 'blackjack', CASE WHEN p_settled THEN 'round_settled' ELSE 'round_action' END,
    CASE WHEN p_settled THEN p_payout - p_additional_bet ELSE -p_additional_bet END,
    v_balance, p_request_id, p_result_id, '{}'::jsonb) RETURNING id INTO v_transaction_id;
  v_response := jsonb_build_object(
    'balance', v_balance, 'xp', v_xp, 'level', v_level, 'rank', v_rank,
    'transactionId', v_transaction_id, 'state', p_new_state,
    'version', p_expected_version + 1, 'settled', p_settled,
    'result', p_result, 'replayed', false
  );
  UPDATE wallet_transactions SET metadata = jsonb_build_object('response', v_response)
    WHERE id = v_transaction_id;
  RETURN v_response;
END;
$$;

REVOKE ALL ON FUNCTION advance_blackjack_round(TEXT, UUID, UUID, UUID, INTEGER, JSONB, NUMERIC, BOOLEAN, NUMERIC, BIGINT, JSONB)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION advance_blackjack_round(TEXT, UUID, UUID, UUID, INTEGER, JSONB, NUMERIC, BOOLEAN, NUMERIC, BIGINT, JSONB)
  TO service_role;