import StyleDictionary from 'style-dictionary';

function toNestedTokenObject(tokens) {
  const root = {};

  for (const token of tokens) {
    const path = token.path;
    let current = root;

    for (const segment of path.slice(0, -1)) {
      current[segment] ??= {};
      current = current[segment];
    }

    current[path.at(-1)] = token.$value ?? token.value;
  }

  return root;
}

StyleDictionary.registerFileHeader({
  name: 'casino-generated',
  fileHeader: () => ['This file is generated by Style Dictionary. Do not edit directly.'],
});

StyleDictionary.registerFormat({
  name: 'typescript/nested-const',
  format: ({ dictionary }) => {
    const tokens = toNestedTokenObject(dictionary.allTokens);

    return [
      '/** This file is generated by Style Dictionary. Do not edit directly. */',
      `export const TOKENS = ${JSON.stringify(tokens, null, 2)} as const;`,
      '',
      'export const Z_INDEX = TOKENS.zIndex;',
      '',
    ].join('\n');
  },
});

export default {
  source: ['design/tokens.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'src/styles/',
      files: [
        {
          destination: 'tokens.generated.css',
          format: 'css/variables',
          options: { fileHeader: 'casino-generated' },
        },
      ],
    },
    typescript: {
      transformGroup: 'js',
      buildPath: 'src/lib/design/',
      files: [
        {
          destination: 'tokens.generated.ts',
          format: 'typescript/nested-const',
        },
      ],
    },
  },
};
