/** This file is generated by Style Dictionary. Do not edit directly. */
export const TOKENS = {
  color: {
    canvas: {
      base: '#0b0e14',
      deep: '#05070a',
    },
    gold: {
      primary: '#d4af37',
      secondary: '#f59e0b',
    },
    success: {
      base: '#10b981',
      dark: '#059669',
    },
    error: {
      base: '#ef4444',
      dark: '#dc2626',
    },
    border: {
      glass: '#ffffff1a',
    },
  },
  zIndex: {
    modal: {
      standard: 1000,
      crashTutorial: 2000,
      priority: 5000,
    },
    overlay: {
      bigWin: 9999,
      loadingSplash: 99999,
    },
  },
  radius: {
    sm: '4px',
    md: '8px',
    lg: '12px',
    xl: '20px',
    full: '9999px',
  },
  space: {
    xs: 'clamp(0.25rem, 0.2rem + 0.25vw, 0.5rem)',
    sm: 'clamp(0.5rem, 0.4rem + 0.5vw, 1rem)',
    md: 'clamp(1rem, 0.8rem + 1vw, 2rem)',
    lg: 'clamp(2rem, 1.5rem + 2vw, 4rem)',
    xl: 'clamp(4rem, 3rem + 4vw, 8rem)',
  },
} as const;

export const Z_INDEX = TOKENS.zIndex;
