-- 6.0 Background Jobs: bounded retry state for daily pg_cron wrappers and
-- deduplicated terminal alerts. This migration is additive; it does not run or deploy jobs.
-- Retry contract: three total attempts per (job_name, run_key), with 5m then 15m backoff.
-- Daily race uses the prior UTC day as its run_key, so retries preserve its existing
-- idempotency anchor in public.daily_races rather than settling the next day by accident.

CREATE TABLE IF NOT EXISTS public.background_job_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_name TEXT NOT NULL
    CHECK (job_name IN ('guide_telemetry_purge', 'bet_fingerprint_purge', 'daily_race_settlement')),
  run_key DATE NOT NULL,
  status TEXT NOT NULL DEFAULT 'retry_scheduled'
    CHECK (status IN ('retry_scheduled', 'succeeded', 'dead_letter')),
  attempt_count SMALLINT NOT NULL DEFAULT 0 CHECK (attempt_count BETWEEN 0 AND 3),
  first_started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  next_attempt_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  last_error TEXT,
  alert_enqueued_at TIMESTAMPTZ,
  UNIQUE (job_name, run_key)
);

ALTER TABLE public.background_job_runs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.background_job_runs FROM PUBLIC, anon, authenticated;

-- The table is intentionally only accessed by the server-only functions below. An index is
-- omitted: at most three daily rows are inserted per day, so the unique key is sufficient.

CREATE OR REPLACE FUNCTION public.enqueue_cron_alert(p_job_name TEXT, p_error TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, net, vault, pg_temp
AS $$
DECLARE
  v_alert_secret TEXT;
BEGIN
  SELECT decrypted_secret INTO v_alert_secret
  FROM vault.decrypted_secrets
  WHERE name = 'cron_alert_secret'
  LIMIT 1;

  IF v_alert_secret IS NULL THEN
    RETURN false;
  END IF;

  PERFORM net.http_post(
    url := 'https://casino-xi-six.vercel.app/api/internal/cron-alert',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-cron-alert-secret', v_alert_secret
    ),
    body := jsonb_build_object(
      'job', left(p_job_name, 128),
      'error', left(p_error, 500)
    )
  );

  -- pg_net only confirms enqueueing the request. The durable terminal state remains queryable
  -- even if the downstream HTTP receiver is unavailable.
  RETURN true;
EXCEPTION WHEN OTHERS THEN
  RETURN false;
END;
$$;

REVOKE ALL ON FUNCTION public.enqueue_cron_alert(TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.enqueue_cron_alert(TEXT, TEXT) TO service_role;

CREATE OR REPLACE FUNCTION public.execute_background_job(p_job_name TEXT, p_run_key DATE)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_attempt SMALLINT;
  v_delay INTERVAL;
  v_error TEXT;
  v_alert_enqueued BOOLEAN;
BEGIN
  -- A second pg_cron worker observes the same due row but never waits behind this run.
  IF NOT pg_try_advisory_xact_lock(
    hashtextextended('background_job:' || p_job_name || ':' || p_run_key::TEXT, 0)
  ) THEN
    RETURN;
  END IF;

  INSERT INTO public.background_job_runs (
    job_name,
    run_key,
    status,
    attempt_count,
    first_started_at,
    last_started_at
  )
  VALUES (p_job_name, p_run_key, 'retry_scheduled', 1, now(), now())
  ON CONFLICT (job_name, run_key) DO UPDATE
  SET
    attempt_count = public.background_job_runs.attempt_count + 1,
    last_started_at = now(),
    last_error = NULL,
    next_attempt_at = NULL
  WHERE public.background_job_runs.status = 'retry_scheduled'
    AND public.background_job_runs.attempt_count < 3
    AND (public.background_job_runs.next_attempt_at IS NULL
      OR public.background_job_runs.next_attempt_at <= now())
  RETURNING attempt_count INTO v_attempt;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  BEGIN
    CASE p_job_name
      WHEN 'guide_telemetry_purge' THEN
        PERFORM public.purge_guide_telemetry_events();
      WHEN 'bet_fingerprint_purge' THEN
        PERFORM public.purge_bet_network_fingerprints();
      WHEN 'daily_race_settlement' THEN
        -- The final date-bound declaration below replaces this compatibility definition.
        -- Keep this initial body resolvable while the migration creates the DATE overload.
        PERFORM public.settle_daily_race();
      ELSE
        RAISE EXCEPTION 'Unsupported background job %', p_job_name;
    END CASE;

    UPDATE public.background_job_runs
    SET
      status = 'succeeded',
      completed_at = now(),
      next_attempt_at = NULL,
      last_error = NULL
    WHERE job_name = p_job_name AND run_key = p_run_key;
  EXCEPTION WHEN OTHERS THEN
    v_error := left(SQLERRM, 500);

    IF v_attempt < 3 THEN
      v_delay := CASE v_attempt
        WHEN 1 THEN interval '5 minutes'
        WHEN 2 THEN interval '15 minutes'
      END;

      UPDATE public.background_job_runs
      SET
        status = 'retry_scheduled',
        next_attempt_at = now() + v_delay,
        last_error = v_error
      WHERE job_name = p_job_name AND run_key = p_run_key;
    ELSE
      UPDATE public.background_job_runs
      SET
        status = 'dead_letter',
        completed_at = now(),
        next_attempt_at = NULL,
        last_error = v_error
      WHERE job_name = p_job_name
        AND run_key = p_run_key
      RETURNING alert_enqueued_at IS NULL INTO v_alert_enqueued;

      -- A terminal lifecycle enqueues at most one Sentry alert. If pg_net cannot enqueue the
      -- request, alert_enqueued_at stays NULL for manual inspection instead of claiming delivery.
      IF COALESCE(v_alert_enqueued, false)
        AND public.enqueue_cron_alert(p_job_name, v_error) THEN
        UPDATE public.background_job_runs
        SET alert_enqueued_at = now()
        WHERE job_name = p_job_name
          AND run_key = p_run_key
          AND alert_enqueued_at IS NULL;
      END IF;
    END IF;
  END;
END;
$$;

REVOKE ALL ON FUNCTION public.execute_background_job(TEXT, DATE) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.execute_background_job(TEXT, DATE) TO service_role;

CREATE OR REPLACE FUNCTION public.retry_failed_background_jobs()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_run RECORD;
BEGIN
  FOR v_run IN
    SELECT job_name, run_key
    FROM public.background_job_runs
    WHERE status = 'retry_scheduled'
      AND next_attempt_at IS NOT NULL
      AND next_attempt_at <= now()
      AND attempt_count < 3
    ORDER BY next_attempt_at ASC
    LIMIT 20
  LOOP
    PERFORM public.execute_background_job(v_run.job_name, v_run.run_key);
  END LOOP;
END;
$$;

REVOKE ALL ON FUNCTION public.retry_failed_background_jobs() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.retry_failed_background_jobs() TO service_role;

-- Retain the existing schedules and permissions; only the error semantics become durable.
CREATE OR REPLACE FUNCTION public.run_guide_telemetry_purge_job()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  PERFORM public.execute_background_job('guide_telemetry_purge', (now() AT TIME ZONE 'utc')::date);
END;
$$;

REVOKE ALL ON FUNCTION public.run_guide_telemetry_purge_job() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.run_guide_telemetry_purge_job() TO service_role;

CREATE OR REPLACE FUNCTION public.run_bet_fingerprint_purge_job()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  PERFORM public.execute_background_job('bet_fingerprint_purge', (now() AT TIME ZONE 'utc')::date);
END;
$$;

REVOKE ALL ON FUNCTION public.run_bet_fingerprint_purge_job() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.run_bet_fingerprint_purge_job() TO service_role;

CREATE OR REPLACE FUNCTION public.run_daily_race_settlement_job()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  PERFORM public.execute_background_job('daily_race_settlement', ((now() AT TIME ZONE 'utc')::date - 1));
END;
$$;

REVOKE ALL ON FUNCTION public.run_daily_race_settlement_job() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.run_daily_race_settlement_job() TO service_role;

DO $$
BEGIN
  PERFORM cron.unschedule('background-job-retry');
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;

SELECT cron.schedule(
  'background-job-retry',
  '*/5 * * * *',
  $$SELECT public.retry_failed_background_jobs();$$
);

-- Existing wallet_events.attempts tracks work performed by its downstream consumer. Delivery
-- attempts are recorded separately so an unavailable pg_net/HTTP boundary also reaches a
-- bounded terminal state without altering the consumer's claim/ack semantics.
ALTER TABLE public.wallet_events
  ADD COLUMN IF NOT EXISTS dead_letter_alerted_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS dispatch_attempts INTEGER NOT NULL DEFAULT 0
    CHECK (dispatch_attempts >= 0);

CREATE OR REPLACE FUNCTION public.alert_wallet_event_dead_letters(
  p_job_name TEXT,
  p_event_ids UUID[]
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF COALESCE(array_length(p_event_ids, 1), 0) = 0 THEN
    RETURN;
  END IF;

  IF public.enqueue_cron_alert(
    p_job_name,
    array_length(p_event_ids, 1) || ' wallet_events reached their retry limit'
  ) THEN
    UPDATE public.wallet_events
    SET dead_letter_alerted_at = now()
    WHERE id = ANY(p_event_ids)
      AND processed_at IS NULL
      AND dead_letter_alerted_at IS NULL;
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.alert_wallet_event_dead_letters(TEXT, UUID[]) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.alert_wallet_event_dead_letters(TEXT, UUID[]) TO service_role;

-- The initial pg_net push is itself an observed delivery attempt. claim_big_win_notify_event()
-- still owns its existing consumer-attempt counter and acknowledgement contract.
CREATE OR REPLACE FUNCTION public.notify_big_win_event()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, net, vault, pg_temp
AS $$
DECLARE
  v_secret TEXT;
BEGIN
  UPDATE public.wallet_events
  SET dispatch_attempts = dispatch_attempts + 1
  WHERE id = NEW.id
    AND event_type = 'big_win_notify'
    AND processed_at IS NULL;

  BEGIN
    SELECT decrypted_secret INTO v_secret
    FROM vault.decrypted_secrets
    WHERE name = 'big_win_event_secret'
    LIMIT 1;

    IF v_secret IS NOT NULL THEN
      PERFORM net.http_post(
        url := 'https://casino-xi-six.vercel.app/api/internal/big-win-events',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'x-big-win-event-secret', v_secret
        ),
        body := jsonb_build_object('eventId', NEW.id)
      );
    END IF;
  EXCEPTION WHEN OTHERS THEN
    NULL;
  END;

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.notify_big_win_event() FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.retry_stale_wallet_events()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_row RECORD;
  v_dead_letter_ids UUID[];
BEGIN
  FOR v_row IN
    SELECT id
    FROM public.wallet_events
    WHERE event_type = 'xp_gain'
      AND processed_at IS NULL
      AND created_at < now() - interval '2 minutes'
      AND attempts < 5
    ORDER BY created_at
    LIMIT 200
  LOOP
    BEGIN
      PERFORM public.apply_xp_gain(v_row.id);
    EXCEPTION WHEN OTHERS THEN
      NULL;
    END;
  END LOOP;

  SELECT array_agg(id) INTO v_dead_letter_ids
  FROM (
    SELECT id
    FROM public.wallet_events
    WHERE event_type = 'xp_gain'
      AND processed_at IS NULL
      AND attempts >= 5
      AND dead_letter_alerted_at IS NULL
    ORDER BY created_at
    LIMIT 200
    FOR UPDATE SKIP LOCKED
  ) AS unreported;

  PERFORM public.alert_wallet_event_dead_letters('wallet_events_retry', v_dead_letter_ids);
END;
$$;

REVOKE ALL ON FUNCTION public.retry_stale_wallet_events() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.retry_stale_wallet_events() TO service_role;

CREATE OR REPLACE FUNCTION public.retry_stale_big_win_events()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, net, vault, pg_temp
AS $$
DECLARE
  v_row RECORD;
  v_secret TEXT;
  v_dead_letter_ids UUID[];
BEGIN
  SELECT decrypted_secret INTO v_secret
  FROM vault.decrypted_secrets
  WHERE name = 'big_win_event_secret'
  LIMIT 1;

  IF v_secret IS NOT NULL THEN
    FOR v_row IN
      SELECT id
      FROM public.wallet_events
      WHERE event_type = 'big_win_notify'
        AND processed_at IS NULL
        AND created_at < now() - interval '2 minutes'
        AND attempts < 5
        AND dispatch_attempts < 5
      ORDER BY created_at
      LIMIT 200
    LOOP
      UPDATE public.wallet_events
      SET dispatch_attempts = dispatch_attempts + 1
      WHERE id = v_row.id
        AND event_type = 'big_win_notify'
        AND processed_at IS NULL
        AND dispatch_attempts < 5;

      BEGIN
        PERFORM net.http_post(
          url := 'https://casino-xi-six.vercel.app/api/internal/big-win-events',
          headers := jsonb_build_object(
            'Content-Type', 'application/json',
            'x-big-win-event-secret', v_secret
          ),
          body := jsonb_build_object('eventId', v_row.id)
        );
      EXCEPTION WHEN OTHERS THEN
        NULL;
      END;
    END LOOP;
  END IF;

  SELECT array_agg(id) INTO v_dead_letter_ids
  FROM (
    SELECT id
    FROM public.wallet_events
    WHERE event_type = 'big_win_notify'
      AND processed_at IS NULL
      AND (attempts >= 5 OR dispatch_attempts >= 5)
      AND dead_letter_alerted_at IS NULL
    ORDER BY created_at
    LIMIT 200
    FOR UPDATE SKIP LOCKED
  ) AS unreported;

  PERFORM public.alert_wallet_event_dead_letters('big_win_events_retry', v_dead_letter_ids);
END;
$$;

REVOKE ALL ON FUNCTION public.retry_stale_big_win_events() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.retry_stale_big_win_events() TO service_role;



-- Final definitions below make the retry contract explicit in the migration's resulting schema.
-- They replace the initial declarations above before the migration completes and are deliberately
-- kept together so a fresh database never exposes an intermediate retry contract.

CREATE OR REPLACE FUNCTION public.settle_daily_race(p_race_date DATE)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_day_start TIMESTAMPTZ;
  v_day_end TIMESTAMPTZ;
  v_winner RECORD;
  v_user users%ROWTYPE;
  v_new_bal NUMERIC(20,2);
  v_prize NUMERIC(20,2);
  v_winners JSONB := '[]'::jsonb;
  v_total NUMERIC(20,2) := 0;
  v_count INTEGER := 0;
BEGIN
  IF p_race_date IS NULL THEN
    RAISE EXCEPTION 'race date is required';
  END IF;

  v_day_start := p_race_date::timestamp AT TIME ZONE 'utc';
  v_day_end := v_day_start + interval '1 day';

  INSERT INTO public.daily_races (race_date) VALUES (p_race_date)
  ON CONFLICT (race_date) DO NOTHING;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', true, 'alreadySettled', true, 'raceDate', p_race_date);
  END IF;

  FOR v_winner IN
    WITH race_day AS (
      SELECT user_id, SUM(wagered) AS wagered, MAX(bet_at) AS last_bet_at
      FROM (
        SELECT user_id,
          COALESCE(
            NULLIF((metadata -> 'response' ->> 'betAmount')::numeric, 0),
            NULLIF((metadata -> 'response' -> 'result' ->> 'amount')::numeric, 0),
            CASE WHEN amount < 0 THEN ABS(amount) ELSE 0 END
          ) AS wagered,
          created_at AS bet_at
        FROM public.wallet_transactions
        WHERE type = 'bet_settled' AND created_at >= v_day_start AND created_at < v_day_end
        UNION ALL
        SELECT user_id, bet_amount, updated_at
        FROM public.game_rounds
        WHERE status = 'SETTLED' AND updated_at >= v_day_start AND updated_at < v_day_end
      ) candidates
      GROUP BY user_id
    )
    SELECT user_id, wagered, last_bet_at,
      ROW_NUMBER() OVER (ORDER BY wagered DESC, last_bet_at ASC, user_id ASC) AS rnk
    FROM race_day
    ORDER BY wagered DESC, last_bet_at ASC, user_id ASC
    LIMIT 3
  LOOP
    SELECT * INTO v_user FROM public.users WHERE id = v_winner.user_id FOR UPDATE;
    IF NOT FOUND THEN CONTINUE; END IF;

    v_prize := (ARRAY[5000.00, 3000.00, 2000.00])[v_winner.rnk];
    v_new_bal := round((v_user.balance + v_prize)::numeric, 2);

    UPDATE public.users SET balance = v_new_bal, updated_at = now() WHERE id = v_winner.user_id;
    INSERT INTO public.wallet_transactions (user_id, game, type, amount, balance_after, metadata)
    VALUES (
      v_winner.user_id,
      'bonus',
      'bonus',
      v_prize,
      v_new_bal,
      jsonb_build_object(
        'source', 'daily_race',
        'raceDate', p_race_date,
        'rank', v_winner.rnk,
        'wagered', round(v_winner.wagered, 2)
      )
    );
    INSERT INTO public.daily_race_winners (race_date, rank, user_id, wagered, prize)
    VALUES (p_race_date, v_winner.rnk, v_winner.user_id, round(v_winner.wagered, 2), v_prize);

    v_winners := v_winners || jsonb_build_object(
      'rank', v_winner.rnk,
      'userId', v_winner.user_id,
      'prize', v_prize
    );
    v_total := v_total + v_winner.wagered;
    v_count := v_count + 1;
  END LOOP;

  UPDATE public.daily_races
  SET total_wagered = round(v_total, 2), participant_count = v_count
  WHERE race_date = p_race_date;

  RETURN jsonb_build_object('ok', true, 'raceDate', p_race_date, 'winners', v_winners);
END;
$$;

REVOKE ALL ON FUNCTION public.settle_daily_race(DATE) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.settle_daily_race(DATE) TO service_role;

CREATE OR REPLACE FUNCTION public.settle_daily_race()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  RETURN public.settle_daily_race(((now() AT TIME ZONE 'utc')::date - 1));
END;
$$;

REVOKE ALL ON FUNCTION public.settle_daily_race() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.settle_daily_race() TO service_role;

CREATE OR REPLACE FUNCTION public.execute_background_job(p_job_name TEXT, p_run_key DATE)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_attempt SMALLINT;
  v_delay INTERVAL;
  v_error TEXT;
  v_alert_enqueued BOOLEAN;
BEGIN
  IF NOT pg_try_advisory_xact_lock(
    hashtextextended('background_job:' || p_job_name || ':' || p_run_key::TEXT, 0)
  ) THEN
    RETURN;
  END IF;

  INSERT INTO public.background_job_runs (
    job_name, run_key, status, attempt_count, first_started_at, last_started_at
  )
  VALUES (p_job_name, p_run_key, 'retry_scheduled', 1, now(), now())
  ON CONFLICT (job_name, run_key) DO UPDATE
  SET
    attempt_count = public.background_job_runs.attempt_count + 1,
    last_started_at = now(),
    last_error = NULL,
    next_attempt_at = NULL
  WHERE public.background_job_runs.status = 'retry_scheduled'
    AND public.background_job_runs.attempt_count < 3
    AND (
      public.background_job_runs.next_attempt_at IS NULL
      OR public.background_job_runs.next_attempt_at <= now()
    )
  RETURNING attempt_count INTO v_attempt;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  BEGIN
    CASE p_job_name
      WHEN 'guide_telemetry_purge' THEN
        PERFORM public.purge_guide_telemetry_events();
      WHEN 'bet_fingerprint_purge' THEN
        PERFORM public.purge_bet_network_fingerprints();
      WHEN 'daily_race_settlement' THEN
        PERFORM public.settle_daily_race(p_run_key);
      ELSE
        RAISE EXCEPTION 'Unsupported background job %', p_job_name;
    END CASE;

    UPDATE public.background_job_runs
    SET
      status = 'succeeded',
      completed_at = now(),
      next_attempt_at = NULL,
      last_error = NULL
    WHERE job_name = p_job_name AND run_key = p_run_key;
  EXCEPTION WHEN OTHERS THEN
    v_error := left(SQLERRM, 500);

    IF v_attempt < 3 THEN
      v_delay := CASE v_attempt
        WHEN 1 THEN interval '5 minutes'
        WHEN 2 THEN interval '15 minutes'
      END;

      UPDATE public.background_job_runs
      SET
        status = 'retry_scheduled',
        next_attempt_at = now() + v_delay,
        last_error = v_error
      WHERE job_name = p_job_name AND run_key = p_run_key;
    ELSE
      UPDATE public.background_job_runs
      SET
        status = 'dead_letter',
        completed_at = now(),
        next_attempt_at = NULL,
        last_error = v_error
      WHERE job_name = p_job_name
        AND run_key = p_run_key
      RETURNING alert_enqueued_at IS NULL INTO v_alert_enqueued;

      IF COALESCE(v_alert_enqueued, false)
        AND public.enqueue_cron_alert(p_job_name, v_error) THEN
        UPDATE public.background_job_runs
        SET alert_enqueued_at = now()
        WHERE job_name = p_job_name
          AND run_key = p_run_key
          AND alert_enqueued_at IS NULL;
      END IF;
    END IF;
  END;
END;
$$;

REVOKE ALL ON FUNCTION public.execute_background_job(TEXT, DATE) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.execute_background_job(TEXT, DATE) TO service_role;

CREATE OR REPLACE FUNCTION public.retry_stale_big_win_events()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, net, vault, pg_temp
AS $$
DECLARE
  v_row RECORD;
  v_secret TEXT;
  v_dead_letter_ids UUID[];
BEGIN
  SELECT decrypted_secret INTO v_secret
  FROM vault.decrypted_secrets
  WHERE name = 'big_win_event_secret'
  LIMIT 1;

  FOR v_row IN
    SELECT id
    FROM public.wallet_events
    WHERE event_type = 'big_win_notify'
      AND processed_at IS NULL
      AND created_at < now() - interval '2 minutes'
      AND attempts < 5
      AND dispatch_attempts < 5
    ORDER BY created_at
    LIMIT 200
    FOR UPDATE SKIP LOCKED
  LOOP
    UPDATE public.wallet_events
    SET dispatch_attempts = dispatch_attempts + 1
    WHERE id = v_row.id
      AND event_type = 'big_win_notify'
      AND processed_at IS NULL
      AND dispatch_attempts < 5;

    IF FOUND AND v_secret IS NOT NULL THEN
      BEGIN
        PERFORM net.http_post(
          url := 'https://casino-xi-six.vercel.app/api/internal/big-win-events',
          headers := jsonb_build_object(
            'Content-Type', 'application/json',
            'x-big-win-event-secret', v_secret
          ),
          body := jsonb_build_object('eventId', v_row.id)
        );
      EXCEPTION WHEN OTHERS THEN
        NULL;
      END;
    END IF;
  END LOOP;

  SELECT array_agg(id) INTO v_dead_letter_ids
  FROM (
    SELECT id
    FROM public.wallet_events
    WHERE event_type = 'big_win_notify'
      AND processed_at IS NULL
      AND (attempts >= 5 OR dispatch_attempts >= 5)
      AND dead_letter_alerted_at IS NULL
    ORDER BY created_at
    LIMIT 200
    FOR UPDATE SKIP LOCKED
  ) AS unreported;

  PERFORM public.alert_wallet_event_dead_letters('big_win_events_retry', v_dead_letter_ids);
END;
$$;

REVOKE ALL ON FUNCTION public.retry_stale_big_win_events() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.retry_stale_big_win_events() TO service_role;
